Negotiated.validate: fix peer-as auto
Handle the peer-as auto case, where neighbor.peer_as is expected to be
None. These prevents the following error triggered by peer-as auto:

<class 'TypeError'>
%d format: a number is required, not NoneType
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/exabgp/reactor/peer.py", line 541, in _run
    for action in self._establish():
  File "/usr/lib64/python3.6/site-packages/exabgp/reactor/peer.py", line 361, in _establish
    self.proto.validate_open()
  File "/usr/lib64/python3.6/site-packages/exabgp/reactor/protocol.py", line 257, in validate_open
    error = self.negotiated.validate(self.neighbor)
  File "/usr/lib64/python3.6/site-packages/exabgp/bgp/message/open/capability/negotiated.py", line 119, in validate
    return (2,2,'ASN in OPEN (%d) did not match ASN expected (%d)' % (self.received_open.asn,neighbor.peer_as))
TypeError: %d format: a number is required, not NoneType