config/env: fix split/join
current code was causing the following error:

TypeError: join() argument must be str or bytes, not 'tuple'

the change is the least invasive as possible, because I'm unsure why
the initial code was such (looking a bit convoluted to me)